-- MySQL Script generated by MySQL Workbench
-- ter 29 set 2020 01:18:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kaora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kaora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kaora` DEFAULT CHARACTER SET utf8 ;
USE `kaora` ;

-- -----------------------------------------------------
-- Table `kaora`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`type_user` (
  `id_type_user` INT NOT NULL AUTO_INCREMENT,
  `type_user` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id_type_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kaora`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL,
  `type_user_id_type_user` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_type_user_idx` (`type_user_id_type_user` ASC),
  CONSTRAINT `fk_user_type_user`
    FOREIGN KEY (`type_user_id_type_user`)
    REFERENCES `kaora`.`type_user` (`id_type_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kaora`.`muscle_assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`muscle_assessment` (
  `id_muscle_assessment` INT NOT NULL AUTO_INCREMENT,
  `muscle_assessment` LONGTEXT NOT NULL,
  `part_body` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id_muscle_assessment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kaora`.`muscle_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`muscle_data` (
  `id_muscle_data` INT NOT NULL AUTO_INCREMENT,
  `muscle_data` FLOAT NOT NULL,
  `active` TINYINT NOT NULL,
  `muscle_assessment_id_muscle_assessment` INT NOT NULL,
  PRIMARY KEY (`id_muscle_data`),
  INDEX `fk_muscle_data_muscle_assessment1_idx` (`muscle_assessment_id_muscle_assessment` ASC),
  CONSTRAINT `fk_muscle_data_muscle_assessment1`
    FOREIGN KEY (`muscle_assessment_id_muscle_assessment`)
    REFERENCES `kaora`.`muscle_assessment` (`id_muscle_assessment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kaora`.`token_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`token_user` (
  `id_token_user` INT NOT NULL AUTO_INCREMENT,
  `token_user` VARCHAR(1000) NOT NULL,
  `active` TINYINT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_token_user`),
  UNIQUE INDEX `token_user_UNIQUE` (`token_user` ASC),
  INDEX `fk_token_user_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_token_user_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `kaora`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kaora`.`refresh_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`refresh_token` (
  `id_refresh_token` INT NOT NULL AUTO_INCREMENT,
  `refresh_token` VARCHAR(1000) NOT NULL,
  `active` TINYINT NOT NULL,
  `token_user_id_token_user` INT NOT NULL,
  PRIMARY KEY (`id_refresh_token`),
  UNIQUE INDEX `refresh_token_UNIQUE` (`refresh_token` ASC),
  INDEX `fk_refresh_token_token_user1_idx` (`token_user_id_token_user` ASC),
  CONSTRAINT `fk_refresh_token_token_user1`
    FOREIGN KEY (`token_user_id_token_user`)
    REFERENCES `kaora`.`token_user` (`id_token_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kaora`.`annotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaora`.`annotation` (
  `id_annotation` INT NOT NULL AUTO_INCREMENT,
  `annotation` LONGTEXT NULL,
  `user_id_user` INT NOT NULL,
  `muscle_assessment_id_muscle_assessment` INT NOT NULL,
  PRIMARY KEY (`id_annotation`),
  INDEX `fk_annotation_user1_idx` (`user_id_user` ASC),
  INDEX `fk_annotation_muscle_assessment1_idx` (`muscle_assessment_id_muscle_assessment` ASC),
  CONSTRAINT `fk_annotation_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `kaora`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annotation_muscle_assessment1`
    FOREIGN KEY (`muscle_assessment_id_muscle_assessment`)
    REFERENCES `kaora`.`muscle_assessment` (`id_muscle_assessment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
